spring:
  datasource:
    password: departmentDb_user_123
    url: jdbc:mysql://localhost:3304/department_db
    username: departmentDb_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  boot:
    message: Hello, Department service updated!!

server:
  port: 8080 #servisin calısacagı port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}
